spring.application.name=smartcampus
server.port=8080

#indhi
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com