spring.application.name=smartcampus
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
server.port=8080
